name: spider-animation
version: '4.0-SNAPSHOT'
main: com.heledron.spideranimation.SpiderAnimationPlugin
api-version: '1.21'

permissions:
  spider-animation.command:
    description: Allows use of the /spider command
    default: op
